### ISSUE TITLE
Toggl Button not appearing on visualstudio.com / dev.azure.com 

### ISSUE THREAD

**Issue by haffinn** [toggl/toggl-button#1178]
### Environment details

* Operation system: Windows 10, Chrome, Chrome canary, Firefox
* Extension version: 1.12.0

The Toggl button does not appear on visualstudio.com. In Chrome I get this error: 

![test](https://user-images.githubusercontent.com/5712338/48011833-9cbe9300-e118-11e8-8913-7411b47e47a4.png)

Don't see these errors in Canary or Firefox but the button does not appear there either way.
I wonder if this is related to new UI after VSTS rebranded as "Azure DevOps".

**Comment by tcrammond** [comment]
Hey @haffinn, thanks for reporting this. It does seem to be a result of the rebrand.

Do I understand correctly that VSTS is always used under the domain `dev.azure.com` now? I'll try to get this fixed in the next release this week. 

For the timebeing, you could workaround the problem by adding a custom domain permission for `dev.azure.com` on the `Visual Studio` integration (if you find there are two `Visual Studio`s in the list for some reason, pick the last one). Custom domain permissions are found at the bottom of the Permissions tab in the extension settings:

![](https://support.toggl.com/wp-content/uploads/2015/11/customdomains.png)

**Comment by haffinn** [comment]
Hey! 
vsts is rebranding and at least for now it's working on `dev.azure.com/{organization}` and on `{organization}.visualstudio.com` (at least for older projects).

I had already added the permission when I reported this but without success. About a week ago I noticed the button was back (without any changes on my end), so it seems to be working fine now.

**Comment by tcrammond** [comment]
Thanks for the update, will close this for now then as things seem stable.
