### ISSUE TITLE
Quickbooks Integration Missing

### ISSUE THREAD

**Issue by TheSoloJake** [toggl/toggl-button#1485]
#### Relevant integration (if any):

Quickbooks (https://quickbooks.intuit.com/) 

### 🐛 Describe the bug

Quickbooks integration appears on the https://toggl.com/tools page, but does not appear as a listed domain in the Integrations portion of the TogglButton extension 

### Other details or context

Reported by [user](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2137598/conversations/23358316647)

**Comment by nidarasheed** [comment]
I asked user where they would like to see the TogglButton, and they replied saying they went with another app instead of Toggl so they don't need this feature :(

Having said that, the current issue is more simple. The QuickBooks integration option isn't available  in the integrations page at all, so if we can add it in, and then show the button on the main screen in QBO somewhere, users who are interested in the integration can start using it and maybe we will get more feedback on other places to include it. :)

**Comment by EmmanVazz** [comment]
https://chrome.google.com/webstore/detail/toggl-button-productivity/oejgccbfbmkkpaidnkphaiaecficdnfn?hl=en

![image](https://user-images.githubusercontent.com/1174973/69511240-12082c00-0f05-11ea-8ec9-4cebddaf960a.png)

This definitely caused some confusion for me. I suggest removing it if there is no integration.

**Comment by tcrammond** [comment]
References to Quickbooks have been removed, as the integration did not exist 🙈 

Converting this issue to feature request
