### ISSUE TITLE
WorkFlowy integration broken

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/toggl-button#1711]
* **OS version**: not important
* **Browser version**: not important
* **Extension version**: Version 1.60.7

#### Relevant integration (if any):

WorkFlowy - workflowy.com

### 🐛 Describe the bug

The Toggl Button no longer appears on WorkFlowy because they had a pretty major rewrite recently

### Expected behaviour

The Toggl Button should appear 

### Other details or context, additional notes:

WorkFlowy is not listed on the [Integrations](https://toggl.com/integrations/) page or the ["Where can I find the Button?"](https://github.com/toggl/toggl-button/wiki/Where-can-I-find-the-Button%3F#wordpress) page

**Comment by VeljkoTN** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097020/conversations/26666943211)

**Comment by BeksOmega** [comment]
Oh hey sweet! I noticed this too and worked on a fix over the weekend.

To cut to the chase: Putting the button in the bullet menu is no longer going to work. The way they're doing their event capturing means I can't catch the click before the menu closes.

Instead I added a minimal button to the top bar:
![NewUI](https://user-images.githubusercontent.com/25440652/80011956-6c3ff580-8481-11ea-8249-3cb77ba1e2c7.png)

When you click it it starts a timer for the bullet you last interacted with. If you haven't interacted with a bullet yet, it starts the timer for the top bullet on the page. You can also see the timer it will start when you hover over it:
![HoverTip](https://user-images.githubusercontent.com/25440652/80011966-7104a980-8481-11ea-8fd6-c74aa3f0b369.gif)

How do you guys feel about that UI/UX? @VeljkoTN ? If you guys feel good about it I can put up a PR. Otherwise I'm cool with reworking stuff :D

(hopefully this will be more future proof as well? who knows haha)
