### ISSUE TITLE
Toggl Button not visible in a section of Todoist

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/toggl-button#1726]
* **OS version**: Windows 10 
* **Browser version**: Chrome 81.0.4044.138 
* **Extension version**: 1.60.9

#### Relevant integration (if any):

https://todoist.com/

### 🐛 Describe the bug

The Button works as expected everywhere except the "Upcoming" view in Todoist. Hovering over tasks will not show the TB icon in that view: 

![image](https://user-images.githubusercontent.com/36152180/82061751-6678b100-96c9-11ea-8079-e130fa063eb3.png)

### Expected behaviour

The TB icon should show up when you hover over a task just like it does on other views/pages in Todoist

### Steps to reproduce

Steps to reproduce the behaviour:
1. Go to https://todoist.com/app/#upcoming
2. Hover over upcoming tasks

**Comment by zdericnina** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2759100/conversations/27248231210)

**Comment by nidarasheed** [comment]
![image](https://user-images.githubusercontent.com/49634673/84111836-1fb87580-aa41-11ea-85ad-8e8f09b4ffb0.png)
The Today View is also missing TB. [Case](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/534741/conversations/27424356591)

**Comment by raj664** [comment]
- OS version: Ubuntu 24.04.1 LTS  
- Browser version: latest
- Extension version: latest

The Toggle track Button works as expected everywhere   in Todoist. Hovering over tasks will not show the TB icon in that view:![Image](https://github.com/user-attachments/assets/937878e8-dfd7-4943-97c6-98761fa05794)


Relevant integration (if any):![Image](https://github.com/user-attachments/assets/838a45f9-2fbf-48eb-be9e-d3143ebdae06)

**Expected behaviour**
_**The TB icon should show up when you hover over a task just like it does on other views/pages in Todoist**_
