### ISSUE TITLE
Button not appearing in some G-suite apps

### ISSUE THREAD

**Issue by kadrihvl** [toggl/toggl-button#1728]
* **OS version**: macOS Catalina 10.15.4
* **Browser version**: Chrome 81.0.4044.138
* **Extension version**: 1.60.9

#### Relevant integration (if any):

Google Inbox - inbox.google.com
Google Mail - mail.google.com
Google Docs - docs.google.com
Possibly also Google Classroom - classroom.google.com
### 🐛 Describe the bug

After ticking mentioned apps from TB Integrations tab, button does not appear in the apps. 
I'm unsure where to look for TB in Google Classroom as it's not included [here](https://github.com/toggl/toggl-button/wiki/Where-can-I-find-the-Button) (neither are Google Keep examples fyi). 
### Steps to reproduce

Steps to reproduce the behaviour:
1. Go to ...
2. ...

**Comment by kadrihvl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3724360/conversations/27101660388)

**Comment by tcrammond** [comment]
I think the integrations seem to be fine, but the integration list has some issues. It'll show all Google integrations as enabled even if you only enabled one of them - and the others will not work. Will look into it

**Comment by lise-toggl** [comment]
I tested the integrations as well and Classroom isn't working, the selector we're using is out of date. @kadrihvl have there been any requests Classroom? I don't know where the button should be so if we had any user feedback that would be helpful. Or maybe we should drop it if no one is using it?

We also need to remove Inbox since that's no longer around.
