### ISSUE TITLE
Projects missing from extension drop down

### ISSUE THREAD

**Issue by dianetoggl** [toggl/toggl-button#2004]
* **OS version**: Windows 10
* **Browser version**: 93.0.4577.63
* **Extension version**: 1.70.4

### 🐛 Describe the bug

One of our users reached out to let us know that she cannot see any projects from the Browser Extension project drop down, she’s on 1.70.4, we have tried to re-sync and also verified that she’s using the correct account, funny thing is, she can see her previous entries on the extension pop-up and these show without entries even though the timer page and Bo shows they do have projects selected.

### Expected behaviour

User should see their projects on the dropdown

### Other details or context

[Slack](https://toggl.slack.com/archives/C9LMUPD9T/p1628728372273200)

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3540765/conversations/106481309657485)

**Comment by LulzAugusto** [comment]
To reproduce:

1. Install the extension and sign in
2. Go to chrome://extensions and inspect background.js of the extension 
3. Go to the "Application" tab and delete the IndexedDB database for the extension
4. Disable and re-enable the extension
5. Projects should be gone 🌬

**Comment by LulzAugusto** [comment]
### Suggestion

Cannot ignore IndexedDB errors and continue the flow here:
https://github.com/toggl/toggl-button/blob/11ea2a88b598fd2dbb09570238da562260b7d421/src/scripts/background.js#L234-L237

And here:
https://github.com/toggl/toggl-button/blob/11ea2a88b598fd2dbb09570238da562260b7d421/src/scripts/settings.js#L216-L220

If the DB is inaccessible the extension is in an error state and the user has to be informed. In addition, trying to upgrade the database version, recreating the stores, and trying another sync might fix the problem. Otherwise, the error state should be kept and the user will have to contact support I guess.

**Comment by LulzAugusto** [comment]
[Bugsnag error](https://app.bugsnag.com/toggl-dot-com/track-browser-extension-toggl-button/errors/6101748c76ee8600089532e6?filters[event.since]=all&sort=events&pivot_tab=event)
☝️ introduced [here](https://github.com/toggl/toggl-button/commit/60ab9e1add1caad771e5f77a6bea514dee80cd7b#)

**Comment by Phenome** [comment]
[Case](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/conversation/106481309704969)
[Slack](https://toggl.slack.com/archives/C9LMUPD9T/p1632819244419400?thread_ts=1631866899.289100&cid=C9LMUPD9T)
