### ISSUE TITLE
Feature request: Pause option

### ISSUE THREAD

**Issue by orschiro** [toggl/toggl-button#297]
Dear all, 

What a great extension, thanks for your work!

The only thing I am missing currently is an option to pause a running time (e.g. to quickly go to the toilet). 

Could such an option be added to the context menu next to `Start timer`, `Settings`,`...`?

Thankfully,

Robert

**Comment by IndrekV** [comment]
This exact functionality is hard to implement as our backend services don't have that functionality. We have duration only mode that can be enabled from the profile view of the web app, but currently Toggl Button is not supporting this. This is because the Toggl Button only starts and stops entries, it does not not anything about past entries and can not continue them.

**Comment by orschiro** [comment]
@IndrekV 

I didn't know how the backend of Toggl was organised. I understood what you were saying. 

Thanks!

**Comment by rizerzero** [comment]
Hi guys ! still no pause feature ?

**Comment by LESSSE** [comment]
I understand what you mean about your backend. Still, a pause feature can be accomplished by creating a new endpoint in the backend for the timer that uses the current backend. The new endpoint holds the entry's information until it is stopped. When paused stops the original entry but holds on to the entry data. When resumed creates a new entry with the same information.
