### ISSUE TITLE
No Toggl button in Taiga at all‽

### ISSUE THREAD

**Issue by jkphl** [toggl/toggl-button#320]
On a freshly installed (self-hosted) [Taiga](https://taiga.io/) instance, we can't find the Toggle button anywhere in the system (although the integration of the  button and Taiga is explicitely advertised on both vendor sites). Unfortunately this is pretty much a show-stopper for us right now ... Please let me know if access to our (still experimental) Taiga instance would help you debugging this.

**Comment by IndrekV** [comment]
Toggl Button works with default domains of every integration. Meaning that out of the box it does not work with self-hosted instances as they are not described in the extension permissions.

Currently there is two ways to use Toggl Button with a custom domain. 
1. Customize and build your own custom version of the Toggl Button. This is described here: http://blog.toggl.com/2014/10/using-toggl-button-chrome-extension-with-custom-domains/
2. Using the nonofficial Toggl Button version with custom domains support. This is a version of Toggl Button that is maintained by the community and kept in sync with the main extension. There may be some differences because it isn't instantly synced but it should be quite up to date. You can get it from: https://chrome.google.com/webstore/detail/toggl-button-for-custom-w/cblhgnnnpnonkonnfcfkfhhkoldjpdno

Hope this helps.

**Comment by jkphl** [comment]
Hey @IndrekV,

sounds good, thanks for the explanation and hints. I will try this out.

Cheers, Joschi
