### ISSUE TITLE
"Time tracked" always shows 00m 00s

### ISSUE THREAD

**Issue by tekvsakdan** [toggl/toggl-button#423]
I have Toggl Button 0.80 installed and "Time Tracked" always shows 00m 00s in Trello cards.

Google Chrome Version 47.0.2526.111 (64-bit)
Ubuntu 15.10

**Comment by IndrekV** [comment]
I've looked into this issue and it seems that this can happen if the project is not automatically assigned. The "Time Tracked" calculation takes account the project and description of the task. If you change the project after starting the timer it will be assigned to another project and the calculation will not take it into account when summing up the time. The best way for this feature to work would be to have identical project name in Toggl and board name in Trello. That way project is assigned at timer start and Time tracked is calculated correctly.

**Comment by odrija** [comment]
Is this functionality going to change in the future? Wouldn't it be more useful to have Toggl display time tracked on any card, since not every project has its board? The good thing about Trello is that it's very flexible and it would be awesome if Toggl wouldn't be limited to a certain use case. I'm not sure about how difficult or time consuming would be such an implementation…

**Comment by IndrekV** [comment]
We will improve this functionality. The current solution is version one. We already have plans to make it work better with different types of cards.

**Comment by tcrammond** [comment]
Closing, any future development will be in #508.
