### ISSUE TITLE
Add support for default project

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggl-button#480]
If default project is defined then that project will be selected if no project matching is available for the used integration.

**Comment by eatskolnikov** [comment]
I'm confused by the description. What i understand by the title is that the user will be able to setup a default project in settings, making it so when they click the button instead of seeing something like this:
![screen shot 2016-03-07 at 7 52 08 pm](https://cloud.githubusercontent.com/assets/1693000/13587385/5211e376-e49e-11e5-9363-834227553642.png)
they'll see something like:
![screen shot 2016-03-07 at 7 52 31 pm](https://cloud.githubusercontent.com/assets/1693000/13587399/5eb09e74-e49e-11e5-9216-836f1041fef3.png)

Am I wrong?

**Comment by IndrekV** [comment]
Similar feature is present in our desktop app. Default project is selected when there is no project while starting the timer. This happens when user:
- starts timer from the dropdown
- Starts timer from a tool that does not have project matching support or the project name in integration does not match name in toggl.
