### ISSUE TITLE
Integrate self-hosted Bitbucker server

### ISSUE THREAD

**Issue by leonmrni** [toggl/toggl-button#609]
Currently bitbucket.org is integrated. The self-hosted variant has different html markup and no access to jQuery so plain javascript must be used.

I think it should be easily possible to integrate this.

**Comment by IndrekV** [comment]
Since Toggl Button 1.0 it is possible to define custom domains in Settings "permissions" tab. This makes it possible to use the integration built for bitbucket.org with any other url. 

![custom_bitbucket](https://cloud.githubusercontent.com/assets/842229/16910314/aba58bc2-4ce0-11e6-9b02-203bdb368d6b.png)

Toggl Button does not use jQuery.

If markup is different than the regular bitbucket.org a new integration must be created. Here's a guide to creating new integrations: https://github.com/toggl/toggl-button/wiki/Adding-new-integrations
