### ISSUE TITLE
Problem with Pomodoro in Firefox

### ISSUE THREAD

**Issue by vedr4n** [toggl/toggl-button#769]
Hey,

There is a problem with the "Stop time tracking when pomodoro time ends" option inside Toggl Button for Firefox. For some reason, visiting the Timer page in the web app causes Pomodoro to stop the timer even when it shouldn't (i.e. when that option is unchecked). Avoid the web app and Pomodoro works as expected. 

To reproduce:
1. Open Firefox, enable Pomodoro, uncheck the "Stop time tracking when pomodoro time ends" option and set it to activate after 1 minute.
2. Start the timer. 
3. Visit the Toggl web app and wait for Pomodoro to kick in. 

After 1 minute the timer will stop even though it should have continued. If you do the same without visiting the web app Timer page the timer will continue running even after Pomodoro kicks in (as it should). 

---
Desk case: 427750

**Comment by hwine** [comment]
Just a thought, since this is a bit of a corner case, AND the chrome web extension works fine. Now that [Firefox supports web extensions](https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/) and will be moving to [web extensions only](https://blog.mozilla.org/addons/2016/11/23/add-ons-in-2017/) by the end of 2017, it might make more sense to just [port the chrome web extension to Firefox](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension).

**Comment by tcrammond** [comment]
This should be resolved in later versions. Please re-open if there are further problems.
