### ISSUE TITLE
"Start Timer doesnt work"

### ISSUE THREAD

**Issue by CrayzCrinkle** [toggl/toggl-button#813]
Please follow this guide when creating a new issue. This speeds up the process of replicating the issue and finding a solution.

### Environment details

Windows 10 / Chrome with toggl extension.

### Expected behavior
Unknown as no instructions on the internet as to how to use this beyond installing.

### Actual behavior
Right clicking on the red start timer within trello does not do anything. Nothing pops up and nothing is added to the card on my trello board. I have ticked the trello.com extension option.

### Steps to reproduce the behavior
Install the extension without knowing hot the extension works.

### Additional details

Please put something on the internet to advise how you are supposed to use this.

**Comment by syko** [comment]
Hi,
In order to use the button you first have to log in by clicking on the icon next to the address bar.
When you're logged out and try using it from the right-click menu there it doesn't do anything indeed. I have created a new issue for that: https://github.com/toggl/toggl-button/issues/819

More information about how to use Toggl Button can be found here: https://support.toggl.com/toggl-button-chrome-extension/
