### ISSUE TITLE
Habitica Integration Gone

### ISSUE THREAD

**Issue by TheSoloJake** [toggl/toggl-button#898]
Based on Desk cases 561810 and 559363, the Habitica integration with the Toggl Button is no longer available. Communication with Habitica Support has verified that a recent website change has eliminated the current integrations.

**Comment by Alys** [comment]
I'm one of Habitica's moderators. I'm commenting here to say that if anyone has questions about Habitica's website, you can post here and I'll see it and try to help, although fixing this issue is probably (I hope!) a fairly simple matter of seeing what new HTML from the website needs to be put into the integration.

If there's nothing in our website's HTML that the integration can use, we might be willing to consider adjusting the website slightly. I can't promise that because I'm not staff but I'd be happy to take a request for it back to the staff for them to consider.

**Comment by 8Mobius8** [comment]
@Alys there is a slight alignment problem, with my solution in #949. Do you have any clever ideas to make it look better? If need be...

<img width="452" alt="screen shot 2018-01-02 at 23 51 26" src="https://user-images.githubusercontent.com/2933379/34509691-06212ff0-f01b-11e7-9e60-a5cb0c841223.png">

**Comment by Alys** [comment]
@8Mobius8 Thanks so much for working on this! Personally I think that looks pretty good as it is, and I'm not actually strong on the new website's CSS code, so I've asked Habitica's staff if they'd like to comment on this.

**Comment by 8Mobius8** [comment]
Updated #949 to include alignment fix using `transform: scale(0.85)`. Hopefully that is okay, result looks like this:

<img width="373" alt="screen shot 2018-01-04 at 21 10 53" src="https://user-images.githubusercontent.com/2933379/34592787-91a5d4ca-f194-11e7-9454-45784a533e0b.png">
<img width="417" alt="screen shot 2018-01-04 at 21 10 42" src="https://user-images.githubusercontent.com/2933379/34592790-93bc334e-f194-11e7-8793-c493a1839a21.png">

**Comment by tcrammond** [comment]
Looks like this is resolved, closing issue 🚀
